name: vikunja_app
description: Vikunja as Flutter cross platform app

version: 0.2.0+200099

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  http: 0.13.4
  after_layout: ^1.1.0
  intl: ^0.17.0
  flutter_local_notifications: ^9.0.0
  rxdart: ^0.23.1
  flutter_native_timezone: ^2.0.0
  flutter_secure_storage: 4.2.1
  datetime_picker_formfield: 2.0.0
  flutter_typeahead: 3.2.5
  build: 2.1.0
  json_serializable: 4.1.4
  petitparser: 4.1.0
  provider: 6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
    version: any
  #test: any
  flutter_launcher_icons: 0.9.2

flutter_icons:
  image_path: "assets/vikunja_logo.png"
  image_path_ios: "assets/vikunja_ios.png"
  android: true
  ios: true
  adaptive_icon_background: "#FF455486"
  adaptive_icon_foreground: "assets/vikunja_logo_adaptive.png"

flutter:
  uses-material-design: true
  assets:
    - assets/graphics/hypnotize.png
    - assets/vikunja_logo.png
    - assets/vikunja_logo_full.png
    - assets/vikunja_logo_full_white.png
  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/quicksand-v7-latin-regular.ttf
